config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'
  get 'profiles/update'
  get 'appointments/index'
  get 'appointments/show'
  get 'appointments/new'
  get 'appointments/edit'
  get 'patients/index'
  get 'patients/show'
  get 'patients/new'
  get 'patients/edit'
  get 'home/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root "home#index"
  resources :patients
  resources :appointments, only: [:index, :create, :destroy]
  get 'appointments/new/:patient_id', to: 'appointments#new', as: 'new_appointment_with_patient'

  resource :profile, only: [:show, :update] # Single profile per user

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Devise modules (if applicable)
  devise :database_authenticatable, :recoverable, :rememberable, :validatable, :trackable

  # Allowlist attributes for Ransack
  def self.ransackable_attributes(auth_object = nil)
    ["id", "email", "created_at", "sign_in_count", "current_sign_in_at", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user  # Patient
  belongs_to :doctor, class_name: "User", foreign_key: "doctor_id"

  validates :date, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["id", "user_id", "doctor_id", "date", "description" ,"created_at", "updated_at"]
  end

  # Define searchable associations (if needed)
  def self.ransackable_associations(auth_object = nil)
    ["user"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  paginates_per 10  # Optional: Sets default per-page limit
  def self.ransackable_attributes(auth_object = nil)
    ["id", "email", "name", "role", "blocked", "created_at", "updated_at"]
  end

  # Allowlist searchable associations
  def self.ransackable_associations(auth_object = nil)
    ["appointments", "doctor", "patients", "photo_attachment", "photo_blob"]
  end

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :appointments, foreign_key: :user_id, dependent: :destroy
  has_many :patients, -> { where(role: 'patient') }, class_name: "User", foreign_key: "doctor_id"
  
  belongs_to :doctor, class_name: "User", foreign_key: "doctor_id", optional: true
  
  has_attached_file :photo, styles: { thumb: "100x100>" },
                    url: "/system/:class/:attachment/:id_partition/:style/:filename",
                    path: ":rails_root/public/system/:class/:attachment/:id_partition/:style/:filename"

  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  validates :email, presence: true, uniqueness: true

  enum role: { admin: 'admin', doctor: 'doctor', patient: 'patient' }
  
  scope :doctors, -> { where(role: 'doctor') }
  scope :patients, -> { where(role: 'patient') }

   # Doctor's Appointments
  has_many :appointments, foreign_key: "doctor_id", dependent: :destroy

  # Patient's Appointments
  has_many :patient_appointments, class_name: "Appointment", foreign_key: "user_id", dependent: :destroy

  def custom_photo_url(style = :original)
    return '' unless photo.exists?

    base_url = Rails.application.routes.default_url_options[:host] || "http://127.0.0.1:3000"

    # Construct the path manually instead of using photo.url(style)
    file_path = "/system/users/photos/#{id.to_s.rjust(9, '0').scan(/\d{3}/).join('/')}/#{style}/#{photo_file_name}"

    "#{base_url}#{file_path}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :check_if_blocked

	def check_if_blocked
	  if current_user && current_user.blocked?
	    sign_out current_user
	    redirect_to new_user_session_path, alert: "Your account has been blocked. Contact Admin."
	  end
	end

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_doctor!
  
  def index
    @appointments = Appointment.where(doctor_id: current_user.try(:id)).order(date: :desc)
  end
  
  def new
    @patient = current_user.patients.find(params[:patient_id])
    @appointment = Appointment.new
  end

  def create
    @patient = current_user.patients.find(params[:patient_id])
    @appointment = @patient.patient_appointments.build(appointment_params)
    @appointment.doctor = current_user

    if @appointment.save
      UserMailer.appointment_scheduled_email(@appointment, @patient).deliver_now
      redirect_to patient_path(@patient), notice: "Appointment added successfully."
    else
      render :new
    end
  end

  def destroy
    @appointment = current_user.appointments.find(params[:id])
    @appointment.destroy
    redirect_to patient_path(@appointment.user), notice: "Appointment canceled."
  end

  private

  def appointment_params
    params.require(:appointment).permit(:date, :description)
  end

  def check_doctor!
    redirect_to root_path, alert: "Access denied!" unless current_user.doctor?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    per   = params[:limit].nil? ? 10 : params[:limit].to_i
    page  = params[:page].nil? ? 1 : params[:page].to_i
    case current_user.role
    
    when "doctor"
      @patients = User.where(role: "patient", :doctor_id => current_user.try(:id)).paginate(page: page, per_page: per)
      
      @appointments = current_user.appointments.order(date: :desc).limit(5)
    when "patient"
      @appointments = current_user.patient_appointments.order(date: :desc).limit(5)
    when "admin"
      @doctors = User.where(role: :doctor).page(params[:page]).per(10)
      @patients = User.where(role: :patient).page(params[:page]).per(10)
      @appointments = Appointment.order(date: :desc).limit(5)
    end
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_doctor!

  def index
    per   = params[:limit].nil? ? 10 : params[:limit].to_i
    page  = params[:page].nil? ? 1 : params[:page].to_i
    @patients = User.where(role: "patient", :doctor_id => current_user.try(:id)).paginate(page: page, per_page: per)
  end

  def new
    @patient = User.new
  end

  def create
    @patient = current_user.patients.build(patient_params)
    @patient.role = "patient"
    @patient.password = SecureRandom.alphanumeric(10)
    if @patient.save
      UserMailer.patient_added_email(@patient).deliver_now
      redirect_to patients_path, notice: "Patient added successfully."
    else
      render :new
    end
  end

  def show
    @patient = current_user.patients.find(params[:id])
    @appointments = @patient.patient_appointments.order(date: :desc)
  end

  private

  def patient_params
    params.require(:user).permit(:name, :email, :photo)
  end

  def check_doctor!
    redirect_to root_path, alert: "Access denied!" unless current_user.doctor?
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to profile_path, notice: "Profile updated successfully."
    else
      render :show
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def bootstrap_class_for(flash_type)
	    case flash_type.to_sym
	    when :notice then "success"
	    when :alert then "danger"
	    when :error then "danger"
	    when :warning then "warning"
	    else "info"
	    end
	end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/appointments/edit.html.erb
<h1>Appointments#edit</h1>
<p>Find me in app/views/appointments/edit.html.erb</p>

app/views/appointments/index.html.erb
<h3>Appointments</h3>
<ul>
  <% @appointments.each do |appointment| %>
    <li>
      With <%= appointment.user.name %> - <%= appointment.date.strftime("%B %d, %Y - %I:%M %p") %>  
      (<%= link_to "Cancel", appointment_path(appointment), method: :delete, data: { confirm: "Are you sure?" } %>)
    </li>
  <% end %>
</ul>

app/views/appointments/new.html.erb
<h2>New Appointment for <%= @patient.name %></h2>

<%= form_for @appointment, url: appointments_path, method: :post do |f| %>
  <input type="hidden" name="patient_id" value="<%= @patient.id %>">
  <div class="mb-3">
    <%= f.label :date %>
    <%= f.datetime_select :date, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="mt-3">
    <%= f.submit "Create Appointment", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/appointments/show.html.erb
<h1>Appointments#show</h1>
<p>Find me in app/views/appointments/show.html.erb</p>

app/views/home/index.html.erb
<% if current_user.present? %>
  <h2>Welcome, <%= current_user.name %></h2>
<% else %>
  <h2>Welcome, Guest</h2>
<% end %>


<% if current_user.doctor? %>
  <h4>Your Patients</h4>
  <ul>
    <% @patients.each do |patient| %>
      <li>
        <%= link_to patient.name, patient_path(patient) %>  
       </li>
    <% end %>
  </ul>

  <h4>Latest Appointments</h4>
  <ul>
    <% @appointments.each do |appointment| %>
      <li style="display: flex;margin-bottom: 20px ;">
        <div style="margin-right: 10px ;"><%= appointment.user.name %> - <%= appointment.date.strftime("%B %d, %Y - %I:%M %p") %>  </div>
        <br>
        <div><%= button_to "Cancel", appointment_path(appointment), method: :delete, data: { confirm: "Are you sure?" } %></div>
      </li>
    <% end %>
  </ul>
<% elsif current_user.patient? %>
  <h4>Your Appointments</h4>
  <ul>
    <% @appointments.each do |appointment| %>
      <li>
        With Dr. <%= appointment.user.name %> - <%= appointment.date.strftime("%B %d, %Y - %I:%M %p") %>  
        (<%= link_to "Cancel", appointment_path(appointment), method: :delete, data: { confirm: "Are you sure?" } %>)
      </li>
    <% end %>
  </ul>
<% elsif current_user.admin? %>
  <h5>Doctors:</h5>
  <ul>
    <% @doctors.each do |doctor| %>
      <li><%= doctor.name %> - <%= doctor.email %></li>
    <% end %>
  </ul>

  <h5>Patients:</h5>
  <ul>
    <% @patients.each do |patient| %>
      <li><%= patient.name %> - <%= patient.email %></li>
    <% end %>
  </ul>

  <h5>Recent Appointments:</h5>
  <ul>
    <% @appointments.each do |appointment| %>
      <li>
        Dr. <%= appointment.doctor.name %> with <%= appointment.patient.name %> -  
        <%= appointment.date.strftime("%B %d, %Y - %I:%M %p") %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title || "HospitalManagement" %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- Bootstrap CSS via CDN -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
      <% flash.each do |type, message| %>
        <div class="alert alert-<%= bootstrap_class_for(type) %>">
          <%= message %>
        </div>
      <% end %>
    </div>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="<%= root_path %>">Hospital Management</a>

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
              <% if user_signed_in? %>
                <% if current_user.doctor? %>
                  <li class="nav-item">
                    <%= link_to "My Patients", patients_path, class: "nav-link" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "Appointments", appointments_path, class: "nav-link" %>
                  </li>
                <% elsif current_user.patient? %>
                  <li class="nav-item">
                    <%= link_to "My Appointments", appointments_path, class: "nav-link" %>
                  </li>
                <% elsif current_user.admin? %>
                  <li class="nav-item">
                    <%= link_to "Admin Dashboard", admin_root_path, class: "nav-link" %>
                  </li>
                <% end %>
                
         
                <li class="nav-item">
                  <%= link_to "My Profile", profile_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to "Login", new_user_session_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
      <div class="container">
        <%= yield %>
      </div>
    


  <!-- Bootstrap JS via CDN -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

app/views/patients/edit.html.erb
<h1>Patients#edit</h1>
<p>Find me in app/views/patients/edit.html.erb</p>

app/views/patients/index.html.erb
<h2>My Patients</h2>

<% if @patients.present? %>
  <table class="table">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Actions</th>
    </tr>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= link_to patient.name, patient_path(patient) %></td>
        <td><%= patient.email %></td>
        <td><%= link_to "View", patient_path(patient), class: "btn btn-primary btn-sm" %></td>
      </tr>
    <% end %>
  </table>

  <%= paginate @patients %>
<% else %>
  <p>No patients found.</p>
<% end %>

<%= link_to "Add Patient", new_patient_path, class: "btn btn-success" %>

app/views/patients/new.html.erb
<h2>Add Patient</h2>

<%= form_for @patient, url: patients_path do |f| %>
  <div class="mb-3">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :photo, "Profile Picture" %>
    <%= f.file_field :photo, class: "form-control" %>
  </div>

  <div class="mt-3">
    <%= f.submit "Add Patient", class: "btn btn-success" %>
  </div>
<% end %>

app/views/patients/show.html.erb
<h2><%= @patient.name %>'s Profile</h2>

<% if @patient.photo.exists? %>
  <p>Profile Picture:</p>
  <%= image_tag @patient.custom_photo_url(:thumb) %>
<% end %>

<h3>Appointments</h3>
<table class="table">
  <tr>
    <th>Date</th>
    <th>Description</th>
    <th>Actions</th>
  </tr>
  <% @appointments.each do |appointment| %>
    <tr>
      <td><%= appointment.date.strftime("%B %d, %Y %H:%M") %></td>
      <td><%= appointment.description %></td>
      <td>
        <%= link_to "Cancel", appointment_path(appointment), method: :delete, class: "btn btn-danger btn-sm", data: { confirm: "Are you sure?" } %>
      </td>
    </tr>
  <% end %>
</table>

<%= link_to "New Appointment", new_appointment_with_patient_path(@patient), class: "btn btn-primary" %>

app/views/profiles/show.html.erb
<h2>My Profile</h2>

<%= form_for @user, url: profile_path, method: :patch, html: { multipart: true } do |f| %>
  <div class="mb-3">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :photo, "Profile Picture" %>
    <%= f.file_field :photo, class: "form-control" %>
  </div>

  <% if @user.photo.exists? %>
    <p>Current Profile Photo:</p>
	<%= image_tag @user.custom_photo_url(:thumb) %>
  <% end %>

  <div class="mt-3">
    <%= f.submit "Update Profile", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/profiles/update.html.erb
<h1>Profiles#update</h1>
<p>Find me in app/views/profiles/update.html.erb</p>

app/views/users/_patient.html.erb
<tr>
  <td><%= patient.name %></td>
  <td><%= patient.email %></td>
  <td>
    <%= link_to "View", user_path(patient), class: "btn btn-sm btn-primary" %>
    <%= link_to "Remove", user_path(patient), method: :delete, class: "btn btn-sm btn-danger" %>
  </td>
</tr>